#!/bin/bash
# Install script for .bashrc settings

INSTALL_DIR="$HOME/.bash"

if [ -d $INSTALL_DIR ]; then
  echo "Looks like you have a $INSTALL_DIR directory installed.  Good job!"
else
  echo "This folder should be named $INSTALL_DIR alternatively you can change the INSTALL_DIR variable"
  exit
fi;

# .inputrc
files=(.bashrc .bash_functions .bash_aliases)
echo "Backing-up and re-writing configurations!"

for x in "${files[@]}" ; do
  if [ -e $HOME/$x ]; then
    mv $HOME/$x "$INSTALL_DIR"/backup/"$x"
    echo "Backing up $HOME/$x to $INSTALL_DIR/backup/$x"
  fi;
  echo "source $INSTALL_DIR/config/$x" > $HOME/$x
done

mv $HOME/.gitconfig "$INSTALL_DIR"/backup/.gitconfig
echo "Changing .gitconfig to use source $INSTALL_DIR/config/.gitconfig"
echo "[include]
          path = $INSTALL_DIR/config/.gitconfig" > $HOME/.gitconfig

echo "Completed!"